import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react";
import { Roboto, Noto_Sans_JP, Noto_Serif_JP, Playfair_Display } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "next-themes";

const playfairDisplayHeading = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-heading",
});

const notoSans = Noto_Sans_JP({ subsets: ["latin"], variable: "--font-sans" });

const notoSerif = Noto_Serif_JP({ subsets: ["latin"], variable: "--font-serif" });

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        "font-body",
        roboto.variable,
        notoSans.variable,
        notoSerif.variable,
        playfairDisplayHeading.variable,
      )}
      suppressHydrationWarning
    >
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
        </ThemeProvider>
        <Analytics />
      </body>
    </html>
  );
}
